apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-ripley-prueba
  labels:
    app: banco-ripley-prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco-ripley-prueba
  template:
    metadata:
      labels:
        app: banco-ripley-prueba
    spec:
      containers:
        - name: bancoripley-prueba
          image: 255091851557.dkr.ecr.us-east-1.amazonaws.com/banco-ripley-prueba:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080