apiVersion: v1
kind: Service
metadata:
  name: banco-ripley-prueba
spec:
  selector:
    app: banco-ripley-prueba
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer